---
title: "brfss_urban"
author: "Gunnar"
date: "12/6/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(haven)
```


loading dataset city 2019
```{r}
library(tidyverse)
library(janitor)
library(haven)

city2019 <- read_xpt("mmsa/MMSA2019.XPT") %>%
  clean_names()

city2019 <- city2019 %>%
  select(mmsa, mmsaname, mmsawt, ageg5yr, sexvar, race, casthm1, ltasth1, chccopd2, ststr) %>%
  mutate(sexvar = factor(sexvar, labels = c("male", "female")), ageg5yr = na_if(ageg5yr, 14), ageg5yr = factor(ageg5yr, labels = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80+")), race = na_if(race, 9), race = factor(race, labels = c("white", "black", "aian", "asian", "pacific islander", "other", "multiracial", "hispanic")), casthm1 = na_if(casthm1, 9), casthm1 = factor(casthm1, labels = c("no", "yes")), ltasth1 = na_if(ltasth1, 9), ltasth1 = factor(ltasth1, labels = c("no", "yes")), chccopd2 = na_if(chccopd2, 9), chccopd2 = na_if(chccopd2, 7), chccopd2 = factor(chccopd2, labels = c("yes", "no"))) %>%
  rename(asthma_ever = ltasth1, asthma_current = casthm1, copd = chccopd2)
```

loading dataset city 2018
```{r}
library(tidyverse)
library(janitor)
library(haven)

city2018 <- read_xpt("mmsa/MMSA2018.XPT") %>%
  clean_names()

city2018 <- city2018 %>%
  select(mmsa, mmsaname, mmsawt, ageg5yr, sex1, race, casthm1, ltasth1, chccopd1, ststr) %>%
  mutate(sex1 = na_if(sex1, 9), sex1 = na_if(sex1, 7), sex1 = factor(sex1, labels = c("male", "female")), ageg5yr = na_if(ageg5yr, 14), ageg5yr = factor(ageg5yr, labels = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80+")), race = na_if(race, 9), race = factor(race, labels = c("white", "black", "aian", "asian", "pacific islander", "other", "multiracial", "hispanic")), casthm1 = na_if(casthm1, 9), casthm1 = factor(casthm1, labels = c("no", "yes")), ltasth1 = na_if(ltasth1, 9), ltasth1 = factor(ltasth1, labels = c("no", "yes")), chccopd1 = na_if(chccopd1, 9), chccopd1 = na_if(chccopd1, 7), chccopd1 = factor(chccopd1, labels = c("yes", "no"))) %>%
  rename(asthma_ever = ltasth1, asthma_current = casthm1, copd = chccopd1, sexvar = sex1)
```

loading dataset city 2017
```{r}
library(tidyverse)
library(janitor)
library(haven)

city2017 <- read_xpt("mmsa/MMSA2017.XPT") %>%
  clean_names()

city2017 <- city2017 %>%
  select(mmsa, mmsaname, mmsawt, ageg5yr, sex, race, casthm1, ltasth1, chccopd1, ststr) %>%
  mutate(sex = na_if(sex, 9), sex = factor(sex, labels = c("male", "female")), ageg5yr = na_if(ageg5yr, 14), ageg5yr = factor(ageg5yr, labels = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80+")), race = na_if(race, 9), race = factor(race, labels = c("white", "black", "aian", "asian", "pacific islander", "other", "multiracial", "hispanic")), casthm1 = na_if(casthm1, 9), casthm1 = factor(casthm1, labels = c("no", "yes")), ltasth1 = na_if(ltasth1, 9), ltasth1 = factor(ltasth1, labels = c("no", "yes")), chccopd1 = na_if(chccopd1, 9), chccopd1 = na_if(chccopd1, 7), chccopd1 = factor(chccopd1, labels = c("yes", "no"))) %>%
  rename(asthma_ever = ltasth1, asthma_current = casthm1, copd = chccopd1, sexvar = sex)
```

loading dataset city 2016
```{r}
library(tidyverse)
library(janitor)
library(haven)

city2016 <- read_xpt("mmsa/MMSA2016.XPT") %>%
  clean_names()

city2016 <- city2016 %>%
  select(mmsa, mmsaname, mmsawt, ageg5yr, sex, race, casthm1, ltasth1, chccopd1, ststr) %>%
  mutate(sex = na_if(sex, 9), sex = factor(sex, labels = c("male", "female")), ageg5yr = na_if(ageg5yr, 14), ageg5yr = factor(ageg5yr, labels = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80+")), race = na_if(race, 9), race = factor(race, labels = c("white", "black", "aian", "asian", "pacific islander", "other", "multiracial", "hispanic")), casthm1 = na_if(casthm1, 9), casthm1 = factor(casthm1, labels = c("no", "yes")), ltasth1 = na_if(ltasth1, 9), ltasth1 = factor(ltasth1, labels = c("no", "yes")), chccopd1 = na_if(chccopd1, 9), chccopd1 = na_if(chccopd1, 7), chccopd1 = factor(chccopd1, labels = c("yes", "no"))) %>%
  rename(asthma_ever = ltasth1, asthma_current = casthm1, copd = chccopd1, sexvar = sex)
```

loading dataset city 2015
```{r}
library(tidyverse)
library(janitor)
library(haven)

city2015 <- read_xpt("mmsa/MMSA2015.XPT") %>%
  clean_names()

city2015 <- city2015 %>%
  select(mmsa, mmsaname, mmsawt, ageg5yr, sex, race, casthm1, ltasth1, chccopd1, ststr) %>%
  mutate(sex = na_if(sex, 9), sex = factor(sex, labels = c("male", "female")), ageg5yr = na_if(ageg5yr, 14), ageg5yr = factor(ageg5yr, labels = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80+")), race = na_if(race, 9), race = factor(race, labels = c("white", "black", "aian", "asian", "pacific islander", "other", "multiracial", "hispanic")), casthm1 = na_if(casthm1, 9), casthm1 = factor(casthm1, labels = c("no", "yes")), ltasth1 = na_if(ltasth1, 9), ltasth1 = factor(ltasth1, labels = c("no", "yes")), chccopd1 = na_if(chccopd1, 9), chccopd1 = na_if(chccopd1, 7), chccopd1 = factor(chccopd1, labels = c("yes", "no"))) %>%
  rename(asthma_ever = ltasth1, asthma_current = casthm1, copd = chccopd1, sexvar = sex)
```

loading dataset state 2014
```{r}
library(tidyverse)
library(janitor)
library(haven)

city2014 <- read_xpt("mmsa/MMSA2014.XPT") %>%
  clean_names()

city2014 <- city2014 %>%
  select(mmsa, mmsaname, mmsawt, ageg5yr, sex, race, casthm1, ltasth1, chccopd1, ststr) %>%
  mutate(sex = na_if(sex, 9), sex = factor(sex, labels = c("male", "female")), ageg5yr = na_if(ageg5yr, 14), ageg5yr = factor(ageg5yr, labels = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80+")), race = na_if(race, 9), race = factor(race, labels = c("white", "black", "aian", "asian", "pacific islander", "other", "multiracial", "hispanic")), casthm1 = na_if(casthm1, 9), casthm1 = factor(casthm1, labels = c("no", "yes")), ltasth1 = na_if(ltasth1, 9), ltasth1 = factor(ltasth1, labels = c("no", "yes")), chccopd1 = na_if(chccopd1, 9), chccopd1 = na_if(chccopd1, 7), chccopd1 = factor(chccopd1, labels = c("yes", "no"))) %>%
  rename(asthma_ever = ltasth1, asthma_current = casthm1, copd = chccopd1, sexvar = sex)
```

loading dataset state 2013
```{r}
library(tidyverse)
library(janitor)
library(haven)

city2013 <- read_xpt("mmsa/MMSA2013.XPT") %>%
  clean_names()

city2013 <- city2013 %>%
  select(mmsa, mmsaname, mmsawt, ageg5yr, sex, race, casthm1, ltasth1, chccopd1, ststr) %>%
  mutate(sex = na_if(sex, 9), sex = factor(sex, labels = c("male", "female")), ageg5yr = na_if(ageg5yr, 14), ageg5yr = factor(ageg5yr, labels = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80+")), race = na_if(race, 9), race = factor(race, labels = c("white", "black", "aian", "asian", "pacific islander", "other", "multiracial", "hispanic")), casthm1 = na_if(casthm1, 9), casthm1 = factor(casthm1, labels = c("no", "yes")), ltasth1 = na_if(ltasth1, 9), ltasth1 = factor(ltasth1, labels = c("no", "yes")), chccopd1 = na_if(chccopd1, 9), chccopd1 = na_if(chccopd1, 7), chccopd1 = factor(chccopd1, labels = c("yes", "no"))) %>%
  rename(asthma_ever = ltasth1, asthma_current = casthm1, copd = chccopd1, sexvar = sex)
```

binding the data set
```{r}
temp_df <- bind_rows("2019" = city2019, "2018" = city2018, "2017" = city2017, "2016" = city2016, "2015" = city2015, "2014" = city2014, "2013" = city2013, .id = "brfss_year")
```

##need to create column seperating mmsas into counties
Load the list of counties by MSA number
```{r}
metrolist <- read_csv("metrolist.csv") %>%
  select(mmsa, fips, county_name) %>%
  separate(county_name, c("county", "state"), ", ")

microlist <- read_csv("microlist.csv") %>%
  select(mmsa, fips, county_name) %>%
  separate(county_name, c("county", "state"), ", ")

metrodiv <- read_csv("metrodiv.csv") %>%
  select(mmsa, fips, county_name) %>%
  separate(county_name, c("county", "state"), ", ")

mmsa_list <- rbind(metrolist, microlist)
mmsa_list <- rbind(mmsa_list, metrodiv)


#fixing the mmsas where the code changed in the time period
temp_df <- temp_df %>%
  mutate(mmsa = as.character(mmsa)) %>%
  mutate(mmsa = ifelse(mmsa == "19380", "19430",
                       ifelse(mmsa == "43524", "47900",
                              ifelse(mmsa == "20524", "39100",
                                     ifelse(mmsa == "17200", "30100", mmsa)))))
```

merging the datalist and the county names
```{r}
brfss_cities <- full_join(temp_df, mmsa_list, by = "mmsa")

#dropping the mmsas in puerto rico
brfss_cities <- brfss_cities %>%
  drop_na()
```

Writing data to a csv
```{r}
write_csv(brfss_cities, "brfss_cities.csv")
```

